### ISSUE TITLE
MusicPlayer uses undefined memory

### ISSUE THREAD

**Issue by matheusmortatti** [matheusmortatti/pico8-emulator#105]
When the AudioUnit starts, it instantiates a new MusicPlayer. However, the MusicPlayer reads memory to get and process all music data at once. Since this is done before cart loading, MusicPlayer reads nothing.

Also, MusicPlayer reads the AudioUnit variable inside the Emulator, which is not defined by that time. That means that it holds a null variable for the audio and so it crashes when you try to start to play music.

One solution would be to initialize the music player when a cart is loaded, after memory has been copied from the cart.

**Comment by egordorichev** [comment]
Oh well, sorry, I missed that somehow. Each module has an `Init()` method, it's called once `Emulator` is set and all Emulator units are loaded. I will introduce `CartLoaded()` method, this should fix this bug.
